version: '3'
services:
  postgres2:
    image: postgres:12.4-alpine
    container_name: postgres2
     #restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: ./config/postgres.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - naat_tech_network_2
  pgadmin:
    image: dpage/pgadmin4:2021-10-06-2
    container_name: pgadmin2
    ports:
      - "5433:80"
    env_file: ./config/pgadmin.env
    #volumes:
      #- $PWD/stored_data/pgadmin/:/var/lib/pgadmin/
      #- $PWD/stored_data/pgadmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db
    networks:
      - naat_tech_network_2


networks:
  naat_tech_network_2:
